## MODULE.bazel
module(
    name = "cv_simon_werner",
    version = "1.0.0",
)
# Add the module dependency
bazel_dep(name = "rules_shell", version = "0.8.0")

# Configure and register the shell toolchain
sh_configure = use_extension("@rules_shell//shell/private/extensions:sh_configure.bzl", "sh_configure")
use_repo(sh_configure, "local_config_shell")
register_toolchains("@local_config_shell//:all")
